The_Wall_Redux/config/routes.rb
Wall::Application.routes.draw do

    resources   :sessions,		only: [:new, :create, :destroy]
    get 		"/signin",  	to: 'sessions#new'
    get 		"/signout", 	to: 'sessions#destroy'
    root        'sessions#new'

    resources   :users,			only: [:index, :new, :create, :show, :destroy]
    get 		"/signup",  	to: 'users#new'

    resources   :posts,			only: [:create, :update, :destroy]
    resources   :comments,		only: [:create, :update, :destroy]


end

The_Wall_Redux/app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :post

  	validates	:content, 	presence:	true,
							length:		{ maximum:	500 }
end

The_Wall_Redux/app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to 	:user
	belongs_to 	:wall, 		class_name: "User"

	has_many	:comments,	dependent:	:destroy

	validates	:content, 	presence:	true,
							length:		{ maximum:	500 }

end

The_Wall_Redux/app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :password

    has_many    :posts,     dependent:  :destroy
    has_many    :comments,  dependent:  :destroy

    email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

    validates :name,		  presence:		  true,
  						            length:			  { maximum:			50 }
    validates :email,		  presence:		  true,
                		      format:			  { with:				email_regex },
                          uniqueness:		{ case_sensitive:	false }
    validates :password, 	presence: 		true,
                          confirmation: true,
                          length:			  { :within => 6..40 }

    before_save :encrypt_password

    def has_password?(submitted_password)
  	     encrypted_password == encrypt(submitted_password)
    end

    # class method that checks whether the user's email and submitted_password are valid
    def self.authenticate(email, submitted_password)
  	    user = find_by_email(email)

   	    return nil if user.nil?
   	    return user if user.has_password?(submitted_password)
    end


    private
  	def encrypt_password
  		# generate a unique salt if it's a new user
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
  	
  		# encrypt the password and store that in the encrypted_password field
  		self.encrypted_password = encrypt(password)
  	end

  	# encrypt the password using both the salt and the passed password
  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end

end

The_Wall_Redux/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

The_Wall_Redux/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    c = Comment.new(comment_params)
    if c.save == false
      flash[:errors] = c.errors.messages
    end
    redirect_to user_path(c.post.wall_id)
  end

  def update
    c = Comment.find(:user_id)
    if c.update(content: :content) == false
      flash[:errors] = c.errors.messages
    end
    redirect_to user_path(c.post.wall_id)
  end

  def destroy
    c = Comment.find(params[:id])
    
    if c.destroy == false
      flash[:errors] = c.errors.messages
    end
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :content)
  end

end

The_Wall_Redux/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		p = Post.new(post_params)
		if p.save == false
            flash[:errors] = p.errors.messages
        end
		redirect_to user_path(p.wall_id)
	end

	def update
		p = Post.find(:user_id)
		if p.update(content: :content) == false
            flash[:errors] = p.errors.messages
        end
		redirect_to user_path(p.wall_id)
	end

	def destroy
        p = Post.find(params[:id])
        
        if p.destroy == false
            flash[:errors] = p.errors.messages
        end
        redirect_to :back
	end

	private
	def post_params
		params.require(:post).permit(:wall_id, :user_id, :content)
	end

end

The_Wall_Redux/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.authenticate(params[:session][:email], params[:session][:password])

  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		render :new
  	else
  		sign_in user
  		redirect_to user
  	end

  end

  def destroy
  	sign_out
  	redirect_to signin_path
  end

end

The_Wall_Redux/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if signed_in?
      @users = User.all.select(:id, :name, :email, :created_at)
    else
      deny_access
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash.now[:error] = "User could not be created."
      render action: "new"
    end
  end

  def show
    if signed_in? 
      @user = User.find(params[:id])
      @author_id = session[:user_id];

      @post = Post.new
      @comment = Comment.new

      @posts = Post.where(wall_id: params[:id])
    else
      deny_access
    end 
  end

  def destroy
    u = User.find(params[:id])
    
    if current_user?(u)
        flash[:notice] = "You really shouldn't delete yourself - it isn't healthy!"
    elsif u.destroy == false
        flash[:errors] = u.errors.messages
    end
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

The_Wall_Redux/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to signin_path, notice: "Please sign in to access this page."
  end

end

The_Wall_Redux/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class='container'>
		<%= yield %>
	</div>
</body>
</html>

The_Wall_Redux/app/views/users/index.html.erb
<a href='/signout' class='right'>Sign Out</a>
<h2>The Wall</h2>
<h4>All Users</h4>

<% if flash[:error] %>
	<p class='error'><%= flash[:error] %></p>
<% elsif flash[:notice] %>
	<p class='notice'><%= flash[:notice] %></p>
<% end %>

<table class='table table-condensed table-striped table-hover'>
	<thead><tr>
		<th>ID</th><th>Name</th><th>Email</th><th>Member Since</th><th>Actions</th>
	</tr><thead>
	<tbody>
<%		@users.each{ | user | %>
		<tr>
			<td><%= user.id %></td>
			<td><a href='<%= user_path(user.id) %>'><%= user.name %></a></td>
			<td><%= user.email %></td>
			<td><%= user.created_at.localtime.strftime('%l:%M %p, %b %e, %Y') %></td>
			<td><a data-toggle='modal' href='#delUserModal' user-id='<%= user.id %>' class='delete-user'>
				Delete
			</a></td>
		</tr>
<%		}	%>
	</tbody>
</table>

<div class='modal fade' id='delUserModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
	    <div class='modal-content'>
	        <div class='modal-header'>
	            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
	            <h4 class='modal-title'>Delete User</h4>
	        </div>
	        <div class='modal-body'><h4 class='modal-title'>Are you sure you want to remove this user?  The operation is not reversible.</h4></div>
	        <div class='modal-footer'>
				<form action='/' method='post' id='modal-form'>
	            	<a href='#' class='btn btn-success' data-dismiss='modal'>Cancel</a>
					<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>' />
					<input type='hidden' name='_method' value='delete' />
					<input type='submit' class='btn btn-danger' value='Remove' />
				</form>
	        </div>
	    </div>
    </div>
</div>

The_Wall_Redux/app/views/users/new.html.erb
<h2>Sign Up</h2>
<h4>Already a member? <a href='<%= new_session_path %>'>Sign in!</a></h4>

<% if flash[:error] %>
	<p class='error'><%= flash[:error] %></p>
<% elsif flash[:notice] %>
	<p class='notice'><%= flash[:notice] %></p>
<% end %>

<%= simple_form_for(@user, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit 'Sign Up', class: 'btn-primary form-button' %>
<% end %>

The_Wall_Redux/app/views/users/show.html.erb
<div class='row'>
	<div class='col-xs-6'>
		<h2 class='banner-header'>The Wall</h2>
		<h4><%= @user.name %>'s page</h4>
	</div>
	<div class='col-xs-6'>
		<p class='text-right'><a href='/signout'>Sign Out</a></p>
		<p class='text-right'><a href='/users'>All Users</a></p>
	</div>
</div>

<% if flash[:error] %>
	<p class='error'><%= flash[:error] %></p>
<% elsif flash[:notice] %>
	<p class='notice'><%= flash[:notice] %></p>
<% end %>

<h3>Post a message</h3>
<%= simple_form_for @post, url: '/posts', defaults: { input_html: { class: 'form-control' } }, html: {class: 'form-horizontal' } do |p| %>
	<%= p.input :user_id, as: :hidden, input_html: { value: @author_id } %>
	<%= p.input :wall_id, as: :hidden, input_html: { value: @user.id } %>
	<%= p.input :content %>
	<%= p.submit 'Post a message', class: 'btn-primary form-button' %>
<% end %>

<% 	if @posts.length > 0 %>
<%		@posts.reverse.each{ | post | %>
		<hr />
		<div class='msg-header'>
			<a href='<%= user_path(post.user.id) %>'><%= post.user.name %></a> - <%= post.created_at.localtime.strftime('%l:%M %p, %b %e, %Y') %>
		</div>
		<p>	
			<%= post.content %>
			<a data-toggle='modal' href='#delMsgModal' post-id='<%= post.id %>' class='delete-post'>Delete</a>
		</p>
		<div class='indent-comments'>
<% 			if post.comments.length > 0 
				post.comments.each{ | comment | %>
				<div class='msg-header'>
					<a href='<%= user_path(comment.user.id) %>'>
						<%= comment.user.name %>
					</a>
					- <%= comment.created_at.localtime.strftime('%l:%M %p, %b %e, %Y') %>
				</div>
				<p>	
					<%= comment.content %>
					<a data-toggle='modal' href='#delMsgModal' cmd-id='<%= comment.id %>' class='delete-cmt'>Delete</a>
				</p>
<%				}
	 		end		%>
			<h4>Comment on this post</h4>
			<%= simple_form_for @comment, url: '/comments', defaults: { input_html: { class: 'form-control' } }, html: {class: 'form-horizontal' } do |p| %>
				<%= p.input :user_id, as: :hidden, input_html: { value: @author_id } %>
				<%= p.input :post_id, as: :hidden, input_html: { value: post.id } %>
				<%= p.input :content %>
				<%= p.submit 'Post a comment', class: 'btn-primary form-button' %>
			<% end %>
		</div>
<%		}	%>
<br />
<% 	end	%>

<div class='modal fade' id='delMsgModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
	    <div class='modal-content'>
	        <div class='modal-header'>
	            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
	            <h4 class='modal-title'>Remove</h4>
	        </div>
	        <div class='modal-body'><h4 class='modal-title'>Are you sure you want to remove this message?  The operation is not reversible.</h4></div>
	        <div class='modal-footer'>
				<form action='/' method='post' id='modal-form'>
	            	<a href='#' class='btn btn-success' data-dismiss='modal'>Cancel</a>
					<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>' />
					<input type='hidden' name='_method' value='delete' />
					<input type='submit' class='btn btn-danger' value='Remove' />
				</form>
	        </div>
	    </div>
    </div>
</div>